# Generated by Django 5.1.1 on 2024-09-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_auteur_article_auteur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auteur',
            options={'permissions': [('Peut_Modifier_Article', 'peut modifier un article')]},
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_publication',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=150),
        ),
    ]
